language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - npm install -g bower grunt-cli
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
install: true
script: travis-build/travis-build.sh $TARGET
matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=deploy
    - jdk: oraclejdk7
      env: TARGET=sonarqube
    - jdk: oraclejdk8
      env: TARGET=checker
      # firefox
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=firefox SAUCELABS_BROWSER_VERSION=
      # chrome
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=chrome SAUCELABS_BROWSER_VERSION=
      # safari
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.9" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=7
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.8" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=6
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.6" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=5
      # internet explorer
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 8.1" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=11
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 8" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=10
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=11
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=10
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=9
env:
  global:
    - SONATYPE_USERNAME=trask
    # SONATYPE_PASSWORD, only used for mvn deploy from glowroot/glowroot master branch
    - secure: "YzGuP91Q/7L6rWXUvbGYqr+adYDXA7Cz8CwYjDhRiNK+M48Ta9s3gVbRzgrXyyACERZfrS8t1tqyk0broQiXp8YRSZIK2afjAYq+wI8xWKJsBGspv2Db77zavXEhfezdmnEd5GFMqtKpws2QRDwfJjkIiFBis+ZkUlNRMlFX0PM="
    # SONARQUBE_DB_PASSWORD, only used for mvn sonar:sonar from glowroot/glowroot master branch
    - secure: "TltnDS/ZNZWh/2Wdag9JGb3Xk9mZI9gFri7iNoOGcCKWnQ4UV+YNrlLHEG/Q3xrmnCxMwLjYZNEcUC8qHnxvwK9lxYgBi4ilWTxLJtpimJr2sASroQVq8dwgwLRrJLDZXInykaznlD6yBobO4L85OsdYuavabeP8Bq7ODbjQR0U="
  matrix:
    - TARGET=test GLOWROOT_UNSHADED=false GLOWROOT_HARNESS=javaagent
    - TARGET=test GLOWROOT_UNSHADED=false GLOWROOT_HARNESS=local
    - TARGET=test GLOWROOT_UNSHADED=true GLOWROOT_HARNESS=javaagent
    - TARGET=test GLOWROOT_UNSHADED=true GLOWROOT_HARNESS=local
before_deploy:
  - mkdir -p s3/snapshots/latest
  - cp distribution/target/glowroot-dist.zip s3/snapshots/latest
  - "cp s3/snapshots/latest/glowroot-dist.zip s3/snapshots/glowroot-dist-${TRAVIS_COMMIT:0:10}.zip"
  - cd s3
deploy:
  provider: s3
  access_key_id:
    secure: "TKm8rMaM7//dszw+GpTj+HzZ5BXdiYZmG/EpMRTIy1uKHnXvw5Lf63B1rOQjUclnwqYHSV1r890XHUPeIZddcxJK9nRaOmVg/5AUZIh/HbjqT+M91OkX4SIQiyW+HV2aF5LF+RPTVIB24NbSok3jrZnPRRVGX6VjeEIFYQRXBQY="
  secret_access_key:
    secure: "ItGgSVtNccZaA7BGRDFPmTjw2Gb6R0xLPGbF4F2W1CbUVA+qlW7MaOeQ8jZwlh5O6YelFN2dcehCXbsHnPnkfdl+bCsBJ4QqdSWiCuRYIh0gHFwNjdS7syJ3/T55nhrhSzd398R/IquSbSSk/s2UkpUoAj4NgmIqrlt8MScaslU="
  bucket: glowroot
  skip_cleanup: true
  on:
    jdk: oraclejdk8
    branch: master
    repo: glowroot/glowroot
    condition: "$TARGET = deploy"
addons:
  sauce_connect:
    username: glowroot
    access_key:
      secure: "gywACGw1z8xcdNki4UGId8+GMYTMyEZQdwR/cqIVwjYj5FaHQ+kU+ImikXYQx4DJgldUo1/btgXxSwmOXwzo83TtQkG2nLsVB25KJHULHncchpARQF891rH+RjTceaPLtihfxoQd1Efsa8gS4QI2k6yGNRglCMymkrl27ajsJqE="
