# standard environment (sudo: required) is provisioned with 7.5g memory, but has 50 minute time limit for jobs
# container-based environment (sudo: false) is provisioned with only 4g memory, but haven't run into time limit for jobs yet
sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
    # NewRatio is to leave as much memory as possible to old gen
  - echo "MAVEN_OPTS=\"-Xmx768m -XX:NewRatio=20\"" > ~/.mavenrc
install: true
script: build/travis-ci/build.sh $TARGET
cache:
  directories:
  - $HOME/.m2
  - $HOME/.cache/bower
matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=deploy
    - jdk: oraclejdk8
      env: TARGET=checker
      # chrome
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=chrome SAUCELABS_BROWSER_VERSION=
      # firefox
    - jdk: oraclejdk8
      # having trouble with latest firefox (47) on saucelabs
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=firefox SAUCELABS_BROWSER_VERSION=46
      # internet explorer
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=11
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=10
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="Windows 7" SAUCELABS_BROWSER_NAME=iexplore SAUCELABS_BROWSER_VERSION=9
      # safari
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.11" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=9
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.10" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=8
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.9" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=7
    - jdk: oraclejdk8
      env: TARGET=saucelabs SAUCELABS_PLATFORM="OS X 10.8" SAUCELABS_BROWSER_NAME=safari SAUCELABS_BROWSER_VERSION=6
env:
  matrix:
    - TARGET=test SKIP_SHADING=false GLOWROOT_HARNESS=javaagent
    - TARGET=test SKIP_SHADING=false GLOWROOT_HARNESS=local
    - TARGET=test SKIP_SHADING=true GLOWROOT_HARNESS=javaagent
    - TARGET=test SKIP_SHADING=true GLOWROOT_HARNESS=local
addons:
  firefox: "latest"
  sauce_connect:
    # this is needed on android, see https://support.saucelabs.com/customer/en/portal/questions/13056252
    no_ssl_bump_domains: all
