language: java
jdk:
  - oraclejdk7
before_install:
  - npm install -g bower grunt-cli
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
install: true
script: travis-build/travis-build.sh $TARGET
matrix:
  include:
    - jdk: oraclejdk7
      env: TARGET=checker
    - jdk: openjdk6
      env: TARGET=test
env:
  matrix:
    - TARGET=install
  global:
    - SONATYPE_USERNAME=trask
    # SONATYPE_PASSWORD, only used for mvn deploy from glowroot/glowroot master branch
    - secure: "gvo+eXfSRTJRzbINt1MG6BzuBPCwcxPRzPkA1P+YukaLdBSSL+daYTfwtXhisg9tTMrb9qRcvlz6+YhSvY9RPfHYvpRy5L3NLJGVbWb73S2/i/sNejX9NR0x3RFH6Ddmzp7yvAnNRsGr5f5NtX81apnlBSh1dxr1+S2EygYgLgA="
before_deploy:
  - mkdir -p s3/snapshots/latest
  - cp package/target/glowroot-*.jar s3/snapshots/latest
  - rm s3/snapshots/latest/glowroot-*-sources.jar
  - mv s3/snapshots/latest/glowroot-*.jar s3/snapshots/latest/glowroot.jar
  - "cp s3/snapshots/latest/glowroot.jar s3/snapshots/glowroot-${TRAVIS_COMMIT:0:10}.jar"
  - cd s3
deploy:
  provider: s3
  access_key_id:
    secure: "LxhncdLw6KQzZ3QW1B7X/izAB/tjkg5N6CrT5K16jV8iy2HeEBFYjWhJw6himAJBAI1ASBR1L6D2yopnCDSzfu6dDAa/xWitd2stU59Obv4k6CVj85VmOxlK3/P3IlJKy7DpeMZ9tf1GErVYI85HK+tXSlk+UA4iKCaY9nGWis0="
  secret_access_key:
    secure: "EbBNRcwz7p/9JeYPUbzKVkFe1VzWCdfs9zfGBSv2J79LpoDakCwRqnD1RP4kqwgog5AHZicld7YxfyvKaTGYDsL5b5STBXJh1XRtd5+AsPgQUgp+Ftu2D4GtKQ9PVkZ3KduDDbLNjQOLE9G4BseGAVLaBZ7V0TwHHny4Q53sb5k="
  bucket: glowroot
  skip_cleanup: true
  on:
    jdk: oraclejdk7
    branch: master
    repo: glowroot/glowroot
    condition: "$TARGET = install"
